[book]
authors = ["Kaiserkarel"]
language = "en"
multilingual = false
src = "src"
title = "Interop: Principles, Techniques, and Tools"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-css = ["static/custom.css"]
additional-js = [
  "static/mermaid.min.js",
  "static/mermaid-init.js",
  "static/tab.js",
  "static/solidity.min.js",
]

[output.html.code.languages.solidity]
name = "Solidity"
