[book]
authors = ["Kaiserkarel"]
language = "en"
multilingual = false
src = "src"
title = "Interop: Principles, Techniques, and Tools"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-css = ["custom.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js", "tab.js"]
